apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-test
spec:
  selector:
    matchLabels:
      app: py-test
  template:
    metadata:
      labels:
        app: py-test
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/projectid/{imagename}:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
